/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppBaixarRouteImport } from './routes/_authenticated/app.baixar'
import { Route as AuthenticatedAppBibliotecaRouteImport } from './routes/_authenticated/app.biblioteca'
import { Route as AuthenticatedAppComputadorRouteImport } from './routes/_authenticated/app.computador'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppHistoricoRouteImport } from './routes/_authenticated/app.historico'
import { Route as AuthenticatedAppModelosRouteImport } from './routes/_authenticated/app.modelos'
import { Route as AuthenticatedAppNovaAnaliseRouteImport } from './routes/_authenticated/app.nova-analise'
import { Route as AuthenticatedAppPlanoRouteImport } from './routes/_authenticated/app.plano'
import { Route as AuthenticatedAppAnaliseIdRouteImport } from './routes/_authenticated/app.analise.$id'
import { Route as ApiPublicBridgeHeartbeatRouteImport } from './routes/api/public/bridge/heartbeat'
import { Route as ApiPublicBridgeIaRouteImport } from './routes/api/public/bridge/ia'
import { Route as ApiPublicBridgePairRouteImport } from './routes/api/public/bridge/pair'
import { Route as ApiPublicBridgeVersaoRouteImport } from './routes/api/public/bridge/versao'
import { Route as ApiPublicBridgeCommandsIdRouteImport } from './routes/api/public/bridge/commands.$id'
import { Route as ApiPublicBridgeCommandsNextRouteImport } from './routes/api/public/bridge/commands.next'
import { Route as ApiPublicBridgeJobsNextRouteImport } from './routes/api/public/bridge/jobs.next'
import { Route as ApiPublicBridgeJobsIdEventsRouteImport } from './routes/api/public/bridge/jobs.$id.events'
import { Route as ApiPublicBridgeJobsIdUploadUrlRouteImport } from './routes/api/public/bridge/jobs.$id.upload-url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBaixarRoute = AuthenticatedAppBaixarRouteImport.update({
  id: '/baixar',
  path: '/baixar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBibliotecaRoute =
  AuthenticatedAppBibliotecaRouteImport.update({
    id: '/biblioteca',
    path: '/biblioteca',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComputadorRoute =
  AuthenticatedAppComputadorRouteImport.update({
    id: '/computador',
    path: '/computador',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHistoricoRoute =
  AuthenticatedAppHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModelosRoute = AuthenticatedAppModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNovaAnaliseRoute =
  AuthenticatedAppNovaAnaliseRouteImport.update({
    id: '/nova-analise',
    path: '/nova-analise',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlanoRoute = AuthenticatedAppPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnaliseIdRoute =
  AuthenticatedAppAnaliseIdRouteImport.update({
    id: '/analise/$id',
    path: '/analise/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicBridgeHeartbeatRoute =
  ApiPublicBridgeHeartbeatRouteImport.update({
    id: '/api/public/bridge/heartbeat',
    path: '/api/public/bridge/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeIaRoute = ApiPublicBridgeIaRouteImport.update({
  id: '/api/public/bridge/ia',
  path: '/api/public/bridge/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgePairRoute = ApiPublicBridgePairRouteImport.update({
  id: '/api/public/bridge/pair',
  path: '/api/public/bridge/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeVersaoRoute = ApiPublicBridgeVersaoRouteImport.update({
  id: '/api/public/bridge/versao',
  path: '/api/public/bridge/versao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeCommandsIdRoute =
  ApiPublicBridgeCommandsIdRouteImport.update({
    id: '/api/public/bridge/commands/$id',
    path: '/api/public/bridge/commands/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeCommandsNextRoute =
  ApiPublicBridgeCommandsNextRouteImport.update({
    id: '/api/public/bridge/commands/next',
    path: '/api/public/bridge/commands/next',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeJobsNextRoute = ApiPublicBridgeJobsNextRouteImport.update({
  id: '/api/public/bridge/jobs/next',
  path: '/api/public/bridge/jobs/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeJobsIdEventsRoute =
  ApiPublicBridgeJobsIdEventsRouteImport.update({
    id: '/api/public/bridge/jobs/$id/events',
    path: '/api/public/bridge/jobs/$id/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeJobsIdUploadUrlRoute =
  ApiPublicBridgeJobsIdUploadUrlRouteImport.update({
    id: '/api/public/bridge/jobs/$id/upload-url',
    path: '/api/public/bridge/jobs/$id/upload-url',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/baixar': typeof AuthenticatedAppBaixarRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/computador': typeof AuthenticatedAppComputadorRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/app/modelos': typeof AuthenticatedAppModelosRoute
  '/app/nova-analise': typeof AuthenticatedAppNovaAnaliseRoute
  '/app/plano': typeof AuthenticatedAppPlanoRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/analise/$id': typeof AuthenticatedAppAnaliseIdRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/ia': typeof ApiPublicBridgeIaRoute
  '/api/public/bridge/pair': typeof ApiPublicBridgePairRoute
  '/api/public/bridge/versao': typeof ApiPublicBridgeVersaoRoute
  '/api/public/bridge/commands/$id': typeof ApiPublicBridgeCommandsIdRoute
  '/api/public/bridge/commands/next': typeof ApiPublicBridgeCommandsNextRoute
  '/api/public/bridge/jobs/next': typeof ApiPublicBridgeJobsNextRoute
  '/api/public/bridge/jobs/$id/events': typeof ApiPublicBridgeJobsIdEventsRoute
  '/api/public/bridge/jobs/$id/upload-url': typeof ApiPublicBridgeJobsIdUploadUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/baixar': typeof AuthenticatedAppBaixarRoute
  '/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/app/computador': typeof AuthenticatedAppComputadorRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/app/modelos': typeof AuthenticatedAppModelosRoute
  '/app/nova-analise': typeof AuthenticatedAppNovaAnaliseRoute
  '/app/plano': typeof AuthenticatedAppPlanoRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/analise/$id': typeof AuthenticatedAppAnaliseIdRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/ia': typeof ApiPublicBridgeIaRoute
  '/api/public/bridge/pair': typeof ApiPublicBridgePairRoute
  '/api/public/bridge/versao': typeof ApiPublicBridgeVersaoRoute
  '/api/public/bridge/commands/$id': typeof ApiPublicBridgeCommandsIdRoute
  '/api/public/bridge/commands/next': typeof ApiPublicBridgeCommandsNextRoute
  '/api/public/bridge/jobs/next': typeof ApiPublicBridgeJobsNextRoute
  '/api/public/bridge/jobs/$id/events': typeof ApiPublicBridgeJobsIdEventsRoute
  '/api/public/bridge/jobs/$id/upload-url': typeof ApiPublicBridgeJobsIdUploadUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/baixar': typeof AuthenticatedAppBaixarRoute
  '/_authenticated/app/biblioteca': typeof AuthenticatedAppBibliotecaRoute
  '/_authenticated/app/computador': typeof AuthenticatedAppComputadorRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/historico': typeof AuthenticatedAppHistoricoRoute
  '/_authenticated/app/modelos': typeof AuthenticatedAppModelosRoute
  '/_authenticated/app/nova-analise': typeof AuthenticatedAppNovaAnaliseRoute
  '/_authenticated/app/plano': typeof AuthenticatedAppPlanoRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/analise/$id': typeof AuthenticatedAppAnaliseIdRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/ia': typeof ApiPublicBridgeIaRoute
  '/api/public/bridge/pair': typeof ApiPublicBridgePairRoute
  '/api/public/bridge/versao': typeof ApiPublicBridgeVersaoRoute
  '/api/public/bridge/commands/$id': typeof ApiPublicBridgeCommandsIdRoute
  '/api/public/bridge/commands/next': typeof ApiPublicBridgeCommandsNextRoute
  '/api/public/bridge/jobs/next': typeof ApiPublicBridgeJobsNextRoute
  '/api/public/bridge/jobs/$id/events': typeof ApiPublicBridgeJobsIdEventsRoute
  '/api/public/bridge/jobs/$id/upload-url': typeof ApiPublicBridgeJobsIdUploadUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/admin'
    | '/app/baixar'
    | '/app/biblioteca'
    | '/app/computador'
    | '/app/configuracoes'
    | '/app/historico'
    | '/app/modelos'
    | '/app/nova-analise'
    | '/app/plano'
    | '/app/'
    | '/app/analise/$id'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/ia'
    | '/api/public/bridge/pair'
    | '/api/public/bridge/versao'
    | '/api/public/bridge/commands/$id'
    | '/api/public/bridge/commands/next'
    | '/api/public/bridge/jobs/next'
    | '/api/public/bridge/jobs/$id/events'
    | '/api/public/bridge/jobs/$id/upload-url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/baixar'
    | '/app/biblioteca'
    | '/app/computador'
    | '/app/configuracoes'
    | '/app/historico'
    | '/app/modelos'
    | '/app/nova-analise'
    | '/app/plano'
    | '/app'
    | '/app/analise/$id'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/ia'
    | '/api/public/bridge/pair'
    | '/api/public/bridge/versao'
    | '/api/public/bridge/commands/$id'
    | '/api/public/bridge/commands/next'
    | '/api/public/bridge/jobs/next'
    | '/api/public/bridge/jobs/$id/events'
    | '/api/public/bridge/jobs/$id/upload-url'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/baixar'
    | '/_authenticated/app/biblioteca'
    | '/_authenticated/app/computador'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/historico'
    | '/_authenticated/app/modelos'
    | '/_authenticated/app/nova-analise'
    | '/_authenticated/app/plano'
    | '/_authenticated/app/'
    | '/_authenticated/app/analise/$id'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/ia'
    | '/api/public/bridge/pair'
    | '/api/public/bridge/versao'
    | '/api/public/bridge/commands/$id'
    | '/api/public/bridge/commands/next'
    | '/api/public/bridge/jobs/next'
    | '/api/public/bridge/jobs/$id/events'
    | '/api/public/bridge/jobs/$id/upload-url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBridgeHeartbeatRoute: typeof ApiPublicBridgeHeartbeatRoute
  ApiPublicBridgeIaRoute: typeof ApiPublicBridgeIaRoute
  ApiPublicBridgePairRoute: typeof ApiPublicBridgePairRoute
  ApiPublicBridgeVersaoRoute: typeof ApiPublicBridgeVersaoRoute
  ApiPublicBridgeCommandsIdRoute: typeof ApiPublicBridgeCommandsIdRoute
  ApiPublicBridgeCommandsNextRoute: typeof ApiPublicBridgeCommandsNextRoute
  ApiPublicBridgeJobsNextRoute: typeof ApiPublicBridgeJobsNextRoute
  ApiPublicBridgeJobsIdEventsRoute: typeof ApiPublicBridgeJobsIdEventsRoute
  ApiPublicBridgeJobsIdUploadUrlRoute: typeof ApiPublicBridgeJobsIdUploadUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/baixar': {
      id: '/_authenticated/app/baixar'
      path: '/baixar'
      fullPath: '/app/baixar'
      preLoaderRoute: typeof AuthenticatedAppBaixarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/biblioteca': {
      id: '/_authenticated/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AuthenticatedAppBibliotecaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/computador': {
      id: '/_authenticated/app/computador'
      path: '/computador'
      fullPath: '/app/computador'
      preLoaderRoute: typeof AuthenticatedAppComputadorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/historico': {
      id: '/_authenticated/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AuthenticatedAppHistoricoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/modelos': {
      id: '/_authenticated/app/modelos'
      path: '/modelos'
      fullPath: '/app/modelos'
      preLoaderRoute: typeof AuthenticatedAppModelosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nova-analise': {
      id: '/_authenticated/app/nova-analise'
      path: '/nova-analise'
      fullPath: '/app/nova-analise'
      preLoaderRoute: typeof AuthenticatedAppNovaAnaliseRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/plano': {
      id: '/_authenticated/app/plano'
      path: '/plano'
      fullPath: '/app/plano'
      preLoaderRoute: typeof AuthenticatedAppPlanoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analise/$id': {
      id: '/_authenticated/app/analise/$id'
      path: '/analise/$id'
      fullPath: '/app/analise/$id'
      preLoaderRoute: typeof AuthenticatedAppAnaliseIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/bridge/heartbeat': {
      id: '/api/public/bridge/heartbeat'
      path: '/api/public/bridge/heartbeat'
      fullPath: '/api/public/bridge/heartbeat'
      preLoaderRoute: typeof ApiPublicBridgeHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/ia': {
      id: '/api/public/bridge/ia'
      path: '/api/public/bridge/ia'
      fullPath: '/api/public/bridge/ia'
      preLoaderRoute: typeof ApiPublicBridgeIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/pair': {
      id: '/api/public/bridge/pair'
      path: '/api/public/bridge/pair'
      fullPath: '/api/public/bridge/pair'
      preLoaderRoute: typeof ApiPublicBridgePairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/versao': {
      id: '/api/public/bridge/versao'
      path: '/api/public/bridge/versao'
      fullPath: '/api/public/bridge/versao'
      preLoaderRoute: typeof ApiPublicBridgeVersaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/commands/$id': {
      id: '/api/public/bridge/commands/$id'
      path: '/api/public/bridge/commands/$id'
      fullPath: '/api/public/bridge/commands/$id'
      preLoaderRoute: typeof ApiPublicBridgeCommandsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/commands/next': {
      id: '/api/public/bridge/commands/next'
      path: '/api/public/bridge/commands/next'
      fullPath: '/api/public/bridge/commands/next'
      preLoaderRoute: typeof ApiPublicBridgeCommandsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/jobs/next': {
      id: '/api/public/bridge/jobs/next'
      path: '/api/public/bridge/jobs/next'
      fullPath: '/api/public/bridge/jobs/next'
      preLoaderRoute: typeof ApiPublicBridgeJobsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/jobs/$id/events': {
      id: '/api/public/bridge/jobs/$id/events'
      path: '/api/public/bridge/jobs/$id/events'
      fullPath: '/api/public/bridge/jobs/$id/events'
      preLoaderRoute: typeof ApiPublicBridgeJobsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/jobs/$id/upload-url': {
      id: '/api/public/bridge/jobs/$id/upload-url'
      path: '/api/public/bridge/jobs/$id/upload-url'
      fullPath: '/api/public/bridge/jobs/$id/upload-url'
      preLoaderRoute: typeof ApiPublicBridgeJobsIdUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppBaixarRoute: typeof AuthenticatedAppBaixarRoute
  AuthenticatedAppBibliotecaRoute: typeof AuthenticatedAppBibliotecaRoute
  AuthenticatedAppComputadorRoute: typeof AuthenticatedAppComputadorRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppHistoricoRoute: typeof AuthenticatedAppHistoricoRoute
  AuthenticatedAppModelosRoute: typeof AuthenticatedAppModelosRoute
  AuthenticatedAppNovaAnaliseRoute: typeof AuthenticatedAppNovaAnaliseRoute
  AuthenticatedAppPlanoRoute: typeof AuthenticatedAppPlanoRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAnaliseIdRoute: typeof AuthenticatedAppAnaliseIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppBaixarRoute: AuthenticatedAppBaixarRoute,
  AuthenticatedAppBibliotecaRoute: AuthenticatedAppBibliotecaRoute,
  AuthenticatedAppComputadorRoute: AuthenticatedAppComputadorRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppHistoricoRoute: AuthenticatedAppHistoricoRoute,
  AuthenticatedAppModelosRoute: AuthenticatedAppModelosRoute,
  AuthenticatedAppNovaAnaliseRoute: AuthenticatedAppNovaAnaliseRoute,
  AuthenticatedAppPlanoRoute: AuthenticatedAppPlanoRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAnaliseIdRoute: AuthenticatedAppAnaliseIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBridgeHeartbeatRoute: ApiPublicBridgeHeartbeatRoute,
  ApiPublicBridgeIaRoute: ApiPublicBridgeIaRoute,
  ApiPublicBridgePairRoute: ApiPublicBridgePairRoute,
  ApiPublicBridgeVersaoRoute: ApiPublicBridgeVersaoRoute,
  ApiPublicBridgeCommandsIdRoute: ApiPublicBridgeCommandsIdRoute,
  ApiPublicBridgeCommandsNextRoute: ApiPublicBridgeCommandsNextRoute,
  ApiPublicBridgeJobsNextRoute: ApiPublicBridgeJobsNextRoute,
  ApiPublicBridgeJobsIdEventsRoute: ApiPublicBridgeJobsIdEventsRoute,
  ApiPublicBridgeJobsIdUploadUrlRoute: ApiPublicBridgeJobsIdUploadUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
